apps/detector/views.py
from flask import Blueprint, render_template, current_app, send_from_directory, redirect, url_for, flash, request
from flask_login import login_required, current_user
import uuid
from pathlib import Path
import random
import cv2
import torch
import torchvision
from PIL import Image
import numpy as np
from flask_wtf.csrf import generate_csrf

from apps.detector.forms import UploadImageForm, DeleteForm
from apps.app import db
from apps.detector.models import UserImage, UserImageTag
from apps.crud.models import User

dt = Blueprint(
  "detector",
  __name__,
  template_folder="templates"
)

@dt.route("/")
def index():

  user_images = (
    db.session.query(User, UserImage)
      .join(UserImage)
      .filter(User.id == UserImage.user_id)
      .all()
  )

  csrf_token = generate_csrf()
  delete_form = DeleteForm()

  # 태그 일람을 취득한다
  user_image_tag_dict = {}
  for user_image in user_images:
      # 이미지에 연결된 태그 일람을 취득한다
      user_image_tags = (
          db.session.query(UserImageTag)
          .filter(UserImageTag.user_image_id == user_image.UserImage.id)
          .all()
      )
      user_image_tag_dict[user_image.UserImage.id] = user_image_tags

  return render_template("detector/index.html", user_images=user_images, user_image_tag_dict=user_image_tag_dict, csrf_token=csrf_token, delete_form=delete_form)

@dt.route("/images/<path:filename>")
def image_file(filename):
  return send_from_directory(current_app.config["UPLOAD_FOLDER"], filename)

@dt.route("/upload", methods=["GET", "POST"])
@login_required
def upload_image():
  form = UploadImageForm()
  
  if form.validate_on_submit():
    # 업로드된 이미지 파일을 취득한다
    file = form.image.data

    # 파일의 파일명과 확장자를 취득하고, 파일명을 uuid로 변환한다
    ext = Path(file.filename).suffix
    image_uuid_file_name = str(uuid.uuid4()) + ext

    # 이미지를 보존한다
    image_path = Path(current_app.config["UPLOAD_FOLDER"], image_uuid_file_name)
    file.save(image_path)

    # DB에 보존한다
    user_image = UserImage(user_id=current_user.id, image_path=image_uuid_file_name)
    db.session.add(user_image)
    db.session.commit()

    return redirect(url_for("detector.index"))

  return render_template("detector/upload.html", form = form)

def make_color(labels):
    # 테두리 선의 색을 랜덤으로 결정
    colors = [[random.randint(0, 255) for _ in range(3)] for _ in labels]
    color = random.choice(colors)
    return color


def make_line(result_image):
    # 테두리 선을 작성
    line = round(0.002 * max(result_image.shape[0:2])) + 1
    return line


def draw_lines(c1, c2, result_image, line, color):
    # 사각형의 테두리 선을 이미지에 덧붙여 씀
    cv2.rectangle(result_image, c1, c2, color, thickness=line)
    return cv2


def draw_texts(result_image, line, c1, cv2, color, labels, label):
    # 감지한 텍스트 라벨을 이미지에 덧붙여 씀
    display_txt = f"{labels[label]}"
    font = max(line - 1, 1)
    t_size = cv2.getTextSize(display_txt, 0, fontScale=line / 3, thickness=font)[0]
    c2 = c1[0] + t_size[0], c1[1] - t_size[1] - 3
    cv2.rectangle(result_image, c1, c2, color, -1)
    cv2.putText(
        result_image,
        display_txt,
        (c1[0], c1[1] - 2),
        0,
        line / 3,
        [225, 255, 255],
        thickness=font,
        lineType=cv2.LINE_AA,
    )
    return cv2

def exec_detect(target_image_path):
    # 라벨 읽어 들이기
    labels = current_app.config["LABELS"]

    # 이미지 읽어 들이기
    image = Image.open(target_image_path)

    # 이미지 데이터를 텐서형의 수치 데이터로 변환
    image_tensor = torchvision.transforms.functional.to_tensor(image)

    # 학습 완료 모델의 읽어 들이기
    model = torch.load(Path(current_app.root_path, "detector", "model.pt"))

    # 모델의 추론 모드로 전환
    model = model.eval()

    # 추론의 실행
    output = model([image_tensor])[0]
    tags = []
    result_image = np.array(image.copy())

    # 학습 완료 모델이 감지한 각 물체만큼 이미지에 덧붙여 씀
    for box, label, score in zip(output["boxes"], output["labels"], output["scores"]):
        if score > 0.5 and labels[label] not in tags:
            print(score)
            print(labels[label])
            # 테두리 선의 색 결정
            color = make_color(labels)
            # 테두리 선의 작성
            line = make_line(result_image)
            # 감지 이미지의 테두리 선과 텍스트 라벨의 테두리 선의 위치 정보
            c1 = (int(box[0]), int(box[1]))
            c2 = (int(box[2]), int(box[3]))
            # 이미지에 테두리 선을 덧붙여 씀
            cv2 = draw_lines(c1, c2, result_image, line, color)
            # 이미지에 텍스트 라벨을 덧붙여 씀
            cv2 = draw_texts(result_image, line, c1, cv2, color, labels, label)
            tags.append(labels[label])
    if tags:
      # 감지 후의 이미지 파일명을 생성한다
      detected_image_file_name = str(uuid.uuid4()) + ".jpg"

      # 이미지 복사처 패스를 취득한다
      detected_image_file_path = str(
          Path(current_app.config["UPLOAD_FOLDER"], detected_image_file_name)
      )
      # 변환 후의 이미지 파일을 보존처로 복사한다
      cv2.imwrite(detected_image_file_path, cv2.cvtColor(result_image, cv2.COLOR_RGB2BGR))
      return tags, detected_image_file_name
    else:
        return tags, None

def save_detected_image_tags(user_image, tags, detected_image_file_name):
    # 감지 후 이미지의 보존처 패스를 DB에 보존한다
    user_image.image_path = detected_image_file_name
    # 감지 플래그를 True로 한다
    user_image.is_detected = True
    db.session.add(user_image)
    # user_images_tags 레코드를 작성한다
    for tag in tags:
        user_image_tag = UserImageTag(user_image_id=user_image.id, tag_name=tag)
        db.session.add(user_image_tag)
    db.session.commit()

@dt.route("/detect/<string:image_id>", methods=["POST"])
# login_required 데코레이터를 붙여서 로그인 필수로 한다
@login_required
def detect(image_id):
    # user_images 테이블로부터 레코드를 취득한다
    user_image = db.session.query(UserImage).filter(UserImage.id == image_id).first()
    if user_image is None:
        flash("물체 대상의 이미지가 존재하지 않습니다.")
        return redirect(url_for("detector.index"))

    # 물체 검지 대상의 이미지 패스를 취득한다
    target_image_path = Path(current_app.config["UPLOAD_FOLDER"], user_image.image_path)
    # 물체 검지를 실행하여 태그와 변환 후의 이미지 패스를 취득한다
    tags, detected_image_file_name = exec_detect(target_image_path)

    # 감지된 물체가 없을 경우 처리
    if not tags:  # 태그가 비어 있으면 감지된 물체가 없다는 의미
        flash("감지된 물체가 없습니다.")
        return redirect(url_for("detector.index"))

    try:
        # 데이터베이스에 태그와 변환 후의 이미지 패스 정보를 보존한다
        save_detected_image_tags(user_image, tags, detected_image_file_name)
    except Exception as e:
        flash("물체 검지 처리에서 오류가 발생했습니다. ")
        # 롤백한다
        db.session.rollback()
        # 오류 로그 출력
        current_app.logger.error(e)
        return redirect(url_for("detector.index"))
    return redirect(url_for("detector.index"))

@dt.route("/images/delete/<string:image_id>", methods=["POST"])
@login_required
def delete_image(image_id):
    try:
        # user_image_tags 테이블로부터 레코드를 삭제한다
        db.session.query(UserImageTag).filter(
            UserImageTag.user_image_id == image_id
        ).delete()

        # user_images 테이블로부터 레코드를 삭제한다
        db.session.query(UserImage).filter(UserImage.id == image_id).delete()

        db.session.commit()
    except Exception as e:
        flash("이미지 삭제 처리에서 오류가 발생했습니다.")
        # 오류 로그 출력
        current_app.logger.error(e)
        db.session.rollback()
    return redirect(url_for("detector.index"))

@dt.route("/images/search", methods=["GET"])
def search():
    # 이미지 일람을 취득한다
    user_images = db.session.query(User, UserImage).join(
        UserImage, User.id == UserImage.user_id
    )

    # GET 파라미터로부터 검색 워드를 취득한다
    search_text = request.args.get("search")

    user_image_tag_dict = {}
    filtered_user_images = []

    # user_images를 루프하여 user_images에 연결된 정보를 검색한다
    for user_image in user_images:
        # 검색 워드가 빈 경우는 모든 태그를 취득한다
        if not search_text:
            # 태그 일람을 취득한다
            user_image_tags = (
                db.session.query(UserImageTag)
                .filter(UserImageTag.user_image_id == user_image.UserImage.id)
                .all()
            )
        else:
            # 검색 워드로 추출한 태그를 취득한다
            user_image_tags = (
                db.session.query(UserImageTag)
                .filter(UserImageTag.user_image_id == user_image.UserImage.id)
                .filter(UserImageTag.tag_name.like("%" + search_text + "%"))
                .all()
            )

            # 태그를 찾을 수 없었다면 이미지를 반환하지 않는다
            if not user_image_tags:
                continue

            # 태그가 있는 경우는 태그 정보를 다시 취득한다
            user_image_tags = (
                db.session.query(UserImageTag)
                .filter(UserImageTag.user_image_id == user_image.UserImage.id)
                .all()
            )

        # user_image_id를 키로 하는 사전에 태그 정보를 세트한다
        user_image_tag_dict[user_image.UserImage.id] = user_image_tags

        # 추출 결과의 user_image 정보를 배열 세트한다
        filtered_user_images.append(user_image)

    delete_form = DeleteForm()

    return render_template(
        "detector/index.html",
        # 추출한 user_images 배열을 건넨다
        user_images=filtered_user_images,
        # 이미지에 연결된 태그 일람의 사전을 건넨다
        user_image_tag_dict=user_image_tag_dict,
        delete_form=delete_form,
    )

apps/detector/templates/detector/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>detector</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>
<body>
  <!-- 내비게이션 바를 작성한다 -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">　
    <div class="container">
        <a class="navbar-brand " href="{{ url_for('detector.index') }}">detector</a>

        <!-- 이미지 검색 폼을 추가한다 -->
        {% if url_for(request.endpoint) == url_for('detector.index') or
        url_for(request.endpoint) == url_for('detector.search') %}
        <div class="btn-group">
            <form method="GET" action="{{ url_for('detector.search') }}" name="dtSearchForm">
                {% if request.args.get("search") %}
                <input type="search" id="dt-search" class="form-control col-md-12 dt-search" placeholder="검색"
                    name="search" value="{{ request.args.get('search') }}" />
                {% else %}
                <input type="search" id="dt-search" class="form-control col-md-12 dt-search" placeholder="검색"
                    name="search" />
                {% endif %}
            </form>
        </div>
        {% endif %}
        
        <ul class="navbar-nav">
            {% if current_user.is_authenticated %}
            <li class="nav-item">
                <span class="nav-link">{{ current_user.username }}</span>
            </li>
            <li class="nav-item">
                <a href="{{ url_for('auth.logout') }}" class="nav-link">로그아웃</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('auth.signup') }}">회원가입</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('auth.login') }}">로그인</a>
            </li>
            {% endif %}
        </ul>
    </div>
  </nav>
  
  <section class="container">
    {% block content %}
    {% endblock %}
  </section>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

apps/detector/templates/detector/index.html
{% extends "detector/base.html" %}
{% block content %}

<!-- flash 오류를 표시한다 -->
{% with messages = get_flashed_messages() %}
{% if messages %}
<ul>
    {% for message in messages %}
    <li class="flash">{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
{% endwith %}

  <h1>detector index page</h1>
  <!-- 이미지 업로드 화면으로의 링크를 추가한다 -->
  <div class="col-md-10 text-right dt-image-register-btn">
    <a href="{{ url_for('detector.upload_image') }}" class="btn btn-primary">이미지 신규 등록</a>
  </div>

  <!-- 이미지 일람을 표시한다 -->
  {% for user_image in user_images %}
  <div class="card col-md-7 dt-image-content">
    <header class="d-flex justify-content-between">
      <div class="dt-image-username">
        {{ user_image.User.username }}
      </div>
      <!-- 물체 감지 폼을 추가한다 -->
      <div class="d-flex flex-row-reverse">
        <div class="p-2">
          <form action="{{ url_for('detector.delete_image', image_id=user_image.UserImage.id) }}" method="POST">
              {{ delete_form.csrf_token }}
              {% if current_user.id == user_image.User.id %}
              {{ delete_form.submit(class="btn btn-danger") }}
              {% else %}
              {{ delete_form.submit(class="btn btn-danger", disabled="disabled") }}
              {% endif %}
          </form>
        </div>
        <div class="p-2">
            <form action="{{ url_for('detector.detect', image_id=user_image.UserImage.id) }}" method="POST">
                <input type="hidden" name="csrf_token" value="{{ csrf_token }}">
                {% if current_user.id == user_image.User.id and user_image.UserImage.is_detected == False %}
                <input class="btn btn-primary" type="submit" value="감지">
                {% else %}
                <input class="btn btn-primary" type="submit" value="감지" disabled>
                {% endif %}
            </form>
        </div>
    </div>
    </header>
    <section>
      <img src="{{ url_for('detector.image_file', filename=user_image.UserImage.image_path) }}" alt="업로드 이미지" />
    </section>

    <!-- 태그 정보를 표시한다 -->
    <footer>
      {% for tag in user_image_tag_dict[user_image.UserImage.id] %}
      #{{tag.tag_name }}
      {% endfor %}
    </footer>
  </div>
  {% endfor %}
{% endblock %}

apps/detector/templates/detector/upload.html
{% extends "detector/base.html" %}
{% block content %}
<div>
    <h4>이미지 신규 등록</h4>
    <p>업로드하는 이미지를 선택해 주세요</p>
    <form action="{{ url_for('detector.upload_image') }}" method="post" enctype="multipart/form-data"
        novalidate>
        {{ form.csrf_token }}
        <div>
            <label>
                <span> {{ form.image(class="form-control-file") }} </span>
            </label>
        </div>
        {% for error in form.image.errors %}
        <span style="color: red;">{{ error }}</span>
        {% endfor %}
        <hr />
        <div>
            <label> {{ form.submit(class="btn btn-primary") }} </label>
        </div>
    </form>
</div>
{% endblock %}